export const RequiredQGWdbeFields = {
  gwlogin: "",
  amount: "",
  BADDR1: "",
  BZIP1: "",
  post_return_url_approved: "",
  post_return_url_declined: "",
};

export const OptionalQGWdbeFields = {
  trans_method: "",
  ccnum: "",
  ccmo: "",
  ccyr: "",
  aba: "",
  checkacct: "",
  ResponseMethod: "",
  BCUST_EMAIL: "",
  override_email_customer: "",
  override_trans_email: "",
  RestrictKey: "",
  invoice_num: "",
  invoice_description: "",
  CVV2: "",
  CVVtype: "",
  MAXMIND: "",
  ID: "",
  bg_color: "",
  txt_color: "",
  company_logo: "",
  FNAME: "",
  LNAME: "",
  BCITY: "",
  BSTATE: "",
  BCOUNTRY: "",
  phone: "",
  SFNAME: "",
  SLNAME: "",
  SADDR1: "",
  SCITY: "",
  SSTATE: "",
  SZIP1: "",
  SCOUNTRY: "",
  UserVar: "",
  CustomerVar: "",
  header_receipt: "",
  payment_heading: "",
  page_heading: "",
  cust_id: "",
  override_recur: "",
  OverRideRecureDay: "",
  RID: "",
  initial_amount: "",
  recur_times: "",
};
